/-
Copyright (c) 2026 Frederico Guilherme Nogueira. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Frederico Guilherme Nogueira
-/

import Mathlib

/-!
# Filtrations and σ-Algebras for Stochastic Processes

This file defines the foundational measurability and filtration objects used
throughout the mixing library. In particular, we define the past and future
σ-algebras generated by a discrete-time stochastic process and package them
into Mathlib's `Filtration` type.

## Main definitions

* `ProbabilityTheory.futureSigmaAlgebra X t` : the σ-algebra generated by
  `{X s | s ≥ t}`.
* `ProbabilityTheory.pastSigmaAlgebra X t` : the σ-algebra generated by
  `{X s | s ≤ t}`.
* `ProbabilityTheory.naturalFiltration X h_meas` : the natural filtration of `X`,
  i.e. `t ↦ pastSigmaAlgebra X t`.

## Main results

* `ProbabilityTheory.pastSigmaAlgebra_mono` : the past σ-algebra is monotone in `t`.
* `ProbabilityTheory.measurable_pastSigmaAlgebra` : `X t` is measurable with respect
  to `pastSigmaAlgebra X t`.

## References

* Davidson, J. (1994). *Stochastic Limit Theory*. Oxford University Press.
-/

open MeasureTheory Filter Topology
open scoped ENNReal NNReal

namespace ProbabilityTheory

variable {Ω E : Type*} [mΩ : MeasurableSpace Ω] [mE : MeasurableSpace E]

/-! ### Past and future σ-algebras -/

/-- The σ-algebra on `Ω` generated by all values `X s` with `s ≥ t`.
This is the "tail" or "future" σ-algebra of the process from time `t` onwards. -/
def futureSigmaAlgebra (X : ℕ → Ω → E) (t : ℕ) : MeasurableSpace Ω :=
  ⨆ (s : ℕ) (_ : s ≥ t), MeasurableSpace.comap (X s) mE

/-- The σ-algebra on `Ω` generated by all values `X s` with `s ≤ t`.
This is the "history" or "past" σ-algebra of the process up to time `t`. -/
def pastSigmaAlgebra (X : ℕ → Ω → E) (t : ℕ) : MeasurableSpace Ω :=
  ⨆ (s : ℕ) (_ : s ≤ t), MeasurableSpace.comap (X s) mE

/-- The past σ-algebra is monotone: more history yields a larger σ-algebra. -/
lemma pastSigmaAlgebra_mono (X : ℕ → Ω → E) : Monotone (pastSigmaAlgebra X) := by
  intro t₁ t₂ h
  unfold pastSigmaAlgebra
  apply iSup_mono
  intro s
  apply iSup_mono'
  intro hs
  exact ⟨le_trans hs h, le_rfl⟩

/-! ### Natural filtration -/

/-- The natural filtration of a measurable process `X`, defined by
`t ↦ pastSigmaAlgebra X t`. This is the coarsest filtration to which `X` is adapted. -/
def naturalFiltration (X : ℕ → Ω → E) (h_meas : ∀ t, Measurable (X t)) :
    Filtration ℕ mΩ where
  seq        := pastSigmaAlgebra X
  mono'      := pastSigmaAlgebra_mono X
  le' t      := by
    unfold pastSigmaAlgebra
    simp only [iSup_le_iff]
    intro s _ S hS
    rcases hS with ⟨B, hB, rfl⟩
    exact h_meas s hB

/-! ### Measurability lemmas -/

/-- `X t` is measurable with respect to `pastSigmaAlgebra X t`. -/
lemma measurable_pastSigmaAlgebra (X : ℕ → Ω → E) (t : ℕ) :
    @Measurable Ω E (pastSigmaAlgebra X t) mE (X t) := by
  intro S hS
  unfold pastSigmaAlgebra
  have h_le : MeasurableSpace.comap (X t) mE ≤
      ⨆ (s : ℕ) (_ : s ≤ t), MeasurableSpace.comap (X s) mE :=
    le_iSup_of_le t (le_iSup_of_le (le_refl t) le_rfl)
  exact h_le ((X t) ⁻¹' S) ⟨S, hS, rfl⟩

/-- The past σ-algebra is coarser than the ambient measurable space, provided `X` is
measurable. -/
lemma past_le_global (X : ℕ → Ω → E) (hX : ∀ n, Measurable (X n)) (t : ℕ) :
    pastSigmaAlgebra X t ≤ mΩ := by
  unfold pastSigmaAlgebra
  simp only [iSup_le_iff]
  rintro s _ S ⟨B, hB, rfl⟩
  exact hX s hB

/-- The future σ-algebra is coarser than the ambient measurable space, provided `X` is
measurable. -/
lemma future_le_global (X : ℕ → Ω → E) (hX : ∀ n, Measurable (X n)) (t : ℕ) :
    futureSigmaAlgebra X t ≤ mΩ := by
  unfold futureSigmaAlgebra
  simp only [iSup_le_iff]
  rintro s _ S ⟨B, hB, rfl⟩
  exact hX s hB

end ProbabilityTheory
